# the __settings__ block holds configuration values
# a list of them will be stored below
[__settings__]
auth_user = "username"
auth_pass = "very_secret_password"

[simple]
url = "http://localhost:9999/"
x_status_code_equals = 200
