[can_not_connect]
url = "http://thisdoesnotreallyexist.nope"

[simple]
url = "http://localhost:9999/"
x_status_code_equals = 200

[body_contains_str]
url = ["http://localhost:9999/hello_world", "http://localhost:9999/hello_world/"]
x_status_code_equals = 200
x_body_contains = "hello_world"

[body_contains_list]
url = "http://localhost:9999"
x_status_code_equals = 200
x_body_contains = ["Method", "Proto", "Host"]

[body_contains_fail]
url = ["http://localhost:9999/hello_world", "http://localhost:9999/hello_world/"]
x_status_code_equals = 200
x_body_contains = "ciao"

[body_contains_list_fail]
url = "http://localhost:9999"
exp_body_substring = ["Method", "Potato", "Host"]

[headers_contain]
url = "http://localhost:9999"
x_status_code_equals = 200
x_header_key_val = ["Content-Type: text/plain; charset=utf-8", "Transfer-Encoding: chunked"]

[no_404]
url = "http://localhost:9999"
x_status_code_equals = 404
